project:
  type: book
  
book:
  title: "North Carolina sketch: geography, population, income, and education"
  author: "[Daniel Moul](https://dmoul.github.io)"
  date: "April 2, 2023"
  cover-image: "./images/nc-map-pop-density-2020.png"
  cover-image-alt: "Map of North Carolina poplulation density in 2020"
  #cover-image: "./images/800px-Entering_Union_County_on_North_Carolina_Highway_200.jpg"
  #cover-image-alt: "Weclome to North Carolina highway sign"
  page-footer: 
    center: "Copyright 2023 by [Daniel Moul](https://dmoul.github.io). License: [CC-BY 4.0](http://creativecommons.org/licenses/by/4.0/)"
    background: dark
  # navbar:
  #   search: true

profile:
  default: main
  group: 
    - [main, exploration]
# main runs by default if no profile is specified
# see https://quarto.org/docs/projects/profiles.html

execute:
  freeze: auto  # re-render only when source changes

#bibliography: references.bib
license: "CC BY"
appendix-style: default

format:
  html:
    # theme: yeti
    # theme: cosmo
    theme:
      light: flatly
      dark: darkly
    toc: true
    number-sections: true
    number-depth: 3
    code-fold: true
    code-summary: "Show the code"
