---
title: "Notes and TODO"
author: "Daniel Moul"
format: html
---

# Questions

## Data questions

Using tidycensus to get census data and geometry data

* Which demographic data fields exactly?

* From which census data sets?

* Over which years
  - ideally: 1990, 2000, 2010, 2020

* Which areas: census tracts? counties? PUMAs? zip codes?
  - How consistent are the areas over 30 years?
  - not PUMAs
  - let's start with counties, since (1) boundaries haven't changed since 1990 (I assume!); and (2) it's less data


## Implementation questions

* How do I safely add my census key? Double-check what I did before.
 -  Use census_api_key() to add your free CENSUS API key to your .Renviron

* Should I use targets? Is it worth the overhead? Probably.

* Will tidycensus really cache data when using quarto? It didn't seem to be doing that in my nightlight project

https://walker-data.com/tidycensus/articles/spatial-data.html



## Analysis quesitons

What is the best way to represent ordered categories of data in a geographical data set?
  - example: under 18, 18-65, over 60 for each area, for each census
  
Should I make this a shiny app, so it's easier for the user to switch among dimensions of data? If so, where would I host the output?

Should I use observablejs to add interactivity? Will github.io present it OK?


# Notes

From <https://walker-data.com/tidycensus/>:

> To keep up with on-going development of tidycensus and get even more examples of how to use the package, subscribe to the Walker Data email list below. You’ll also get updates on the forthcoming CRC Press book Analyzing the US Census with R, currently available to read online at <https://walker-data.com/census-r/>.






